name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          IMAGE_BRANCH: ${{ github.ref }}
        run: |
          IMG_TAG=$(git log --date="short" --format="${IMAGE_BRANCH##refs/heads/}-%ct-%h" -n 1 ${IMAGE_BRANCH##refs/heads/} | sed 's/\//-/g')
          echo $IMG_TAG
          docker build . -t lukas8219/resgate-poc:$IMG_TAG
          docker image push lukas8219/resgate-poc:$IMG_TAG